### ISSUE TITLE
v1.10.4 on home page not displaying graphs, uploaded or demo; beta working

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#192]
v1.10.4 on the home page does not seem to be working; neither the demos nor the upload file will display a graph; no error message is given.  Nonfunctional in both firefox and chrome.

Beta is working.

**Comment by dondi** [comment]
OK, this is fixed now. The problem was that the node process itself quit unexpectedly. I tracked the issue to a temporary Google Analytics outage. It turns out that even though they are fairly reliable, they are not at 100%, and our code was relying on that.

Instead we need to handle this possibility. The error looks like this:

<pre>
api error { [Error: There was a temporary error. Please try again later.] code: 503 } null

TypeError: Cannot read property 'rows' of null
    at /home/nicole/GRNsight/server/controllers/ga-controller.js:37:24
    at Request._callback (/home/nicole/GRNsight/server/node_modules/googleapis/lib/transporters.js:97:7)
    at Request.self.callback (/home/nicole/GRNsight/server/node_modules/googleapis/node_modules/request/request.js:373:22)  
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/nicole/GRNsight/server/node_modules/googleapis/node_modules/request/request.js:1318:14)   
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/nicole/GRNsight/server/node_modules/googleapis/node_modules/request/request.js:1266:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
</pre>
