### ISSUE TITLE
Sar's not able to run GRN sight locally

### ISSUE THREAD

**Issue by Sarronnn** [dondi/GRNsight#956]
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\util\createHash.js:75:53)
    at Compilation.createHash (C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compilation.js:1645:16)
    at C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compilation.js:924:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\sarro\GRN\GRNsight\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\sarro\GRN\GRNsight\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compilation.js:881:27)
    at C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compiler.js:464:17
    at eval (eval at create (C:\Users\sarro\GRN\GRNsight\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compilation.js:749:12
    at C:\Users\sarro\GRN\GRNsight\node_modules\webpack\lib\Compilation.js:688:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.1
GRNsight server running on port 5000, environment=development
GET / 304 1229.901 ms - -
GET /js/grnsight.min.js 404 9.200 ms - 157
GET /lib/bootstrap.file-input/bootstrap.file-input.js 304 12.973 ms - -
GET /lib/iframeSizer.contentWindow.min.js 304 19.911 ms - -
GET /stylesheets/grnsight.css 200 806.243 ms - 7884
GET /stylesheets/print.css 200 83.913 ms - 417
GET /js/grnsight.min.js 404 14.767 ms - 157
GET /favicon.ico 200 9.813 ms - 1150

**Comment by dondi** [comment]
Here is a possible related issue found on the web, with a possible fix: https://github.com/webpack/webpack/issues/14532
